// <auto-generated />
using System;
using Gestfac.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gestfac.Migrations
{
    [DbContext(typeof(GestfacDbContext))]
    [Migration("20220214180703_Third")]
    partial class Third
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Gestfac.DTOs.PriceUpdateDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("PriceUpdates");
                });

            modelBuilder.Entity("Gestfac.DTOs.ProductDTO", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentPriceUpdateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsSerialized")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.HasIndex("CurrentPriceUpdateId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Gestfac.DTOs.PriceUpdateDTO", b =>
                {
                    b.HasOne("Gestfac.DTOs.ProductDTO", "Product")
                        .WithMany("PriceUpdates")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_PriceUpdates_Products_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Gestfac.DTOs.ProductDTO", b =>
                {
                    b.HasOne("Gestfac.DTOs.PriceUpdateDTO", "CurrentPriceUpdate")
                        .WithMany()
                        .HasForeignKey("CurrentPriceUpdateId")
                        .HasConstraintName("FK_Products_PriceUpdates_CurrentPriceUpdateId");

                    b.Navigation("CurrentPriceUpdate");
                });

            modelBuilder.Entity("Gestfac.DTOs.ProductDTO", b =>
                {
                    b.Navigation("PriceUpdates");
                });
#pragma warning restore 612, 618
        }
    }
}
